// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace OESAppApi.Migrations
{
    [DbContext(typeof(OESAppApiDbContext))]
    [Migration("20240127152335_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Courses.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ABC12",
                            Description = "You will learn basic skill about python",
                            Name = "Python",
                            ShortName = "P"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ABC21",
                            Color = "0xffec6337",
                            Description = "You will learn basic skill about english",
                            Name = "English",
                            ShortName = "E"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CBA12",
                            Color = "0xff00ff00",
                            Description = "You will learn basic skill about java",
                            Name = "Java",
                            ShortName = "J"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Courses.CourseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CourseItem");

                    b.HasDiscriminator<string>("Discriminator").HasValue("CourseItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Courses.CourseXUser", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("CourseId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CourseXUser");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            UserId = 3,
                            UserRole = 1
                        },
                        new
                        {
                            CourseId = 2,
                            UserId = 3,
                            UserRole = 1
                        },
                        new
                        {
                            CourseId = 3,
                            UserId = 3,
                            UserRole = 1
                        },
                        new
                        {
                            CourseId = 1,
                            UserId = 2,
                            UserRole = 0
                        },
                        new
                        {
                            CourseId = 2,
                            UserId = 2,
                            UserRole = 0
                        },
                        new
                        {
                            CourseId = 3,
                            UserId = 2,
                            UserRole = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Devices.DevicePlatform", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DevicePlatform");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            PlatformName = "Other"
                        },
                        new
                        {
                            Id = 1,
                            PlatformName = "Android"
                        },
                        new
                        {
                            Id = 2,
                            PlatformName = "iOS"
                        },
                        new
                        {
                            Id = 3,
                            PlatformName = "Windows"
                        },
                        new
                        {
                            Id = 4,
                            PlatformName = "MacOS"
                        },
                        new
                        {
                            Id = 5,
                            PlatformName = "Linux"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sessions.Session", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DevicePlatformId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsWeb")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Token");

                    b.HasIndex("DevicePlatformId");

                    b.HasIndex("UserId");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("Domain.Entities.Tests.Answers.Answer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("TestSubmissionId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionTestId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "QuestionId", "TestSubmissionId");

                    b.HasIndex("TestSubmissionId");

                    b.HasIndex("QuestionId", "QuestionTestId");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("Domain.Entities.Tests.Questions.Option", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionTestId")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "QuestionId", "QuestionTestId");

                    b.HasIndex("QuestionId", "QuestionTestId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuestionId = 1,
                            QuestionTestId = 1,
                            Points = 3,
                            Text = "Opt A"
                        },
                        new
                        {
                            Id = 2,
                            QuestionId = 1,
                            QuestionTestId = 1,
                            Points = 0,
                            Text = "Opt B"
                        },
                        new
                        {
                            Id = 3,
                            QuestionId = 1,
                            QuestionTestId = 1,
                            Points = 0,
                            Text = "Opt C"
                        },
                        new
                        {
                            Id = 1,
                            QuestionId = 2,
                            QuestionTestId = 1,
                            Points = 3,
                            Text = "Opt A"
                        },
                        new
                        {
                            Id = 2,
                            QuestionId = 2,
                            QuestionTestId = 1,
                            Points = -3,
                            Text = "Opt B"
                        },
                        new
                        {
                            Id = 3,
                            QuestionId = 2,
                            QuestionTestId = 1,
                            Points = 3,
                            Text = "Opt C"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Tests.Questions.Question", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("TestId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "TestId");

                    b.HasIndex("TestId");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TestId = 1,
                            Description = "What is hello?",
                            Name = "Question 1",
                            Points = 3,
                            Type = "pick-one"
                        },
                        new
                        {
                            Id = 2,
                            TestId = 1,
                            Description = "Pick many question.",
                            Name = "Question 2",
                            Points = 6,
                            Type = "pick-many"
                        },
                        new
                        {
                            Id = 3,
                            TestId = 1,
                            Description = "Write hello.",
                            Name = "Question 3",
                            Points = 10,
                            Type = "open"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Tests.TestSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TestId")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.HasIndex("UserId");

                    b.ToTable("TestSubmission");
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Admin",
                            LastName = "Doe",
                            Password = "$2a$11$zze7INAi/ENBWfpwGrIN8OvbmJqZqdCfuuuZAIIAaDV/7XGaTQ4bS",
                            Role = 0,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Teacher",
                            LastName = "Doe",
                            Password = "$2a$11$CvjgvrV2x8vX1rSZhyrPb.0hzX2F/qSL4EU1dKtFj9yeaGqd7GVzm",
                            Role = 1,
                            Username = "teacher"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Student",
                            LastName = "Doe",
                            Password = "$2a$11$mN69wbQYRIherroQGUyTH.ziAddN2nsgHv74JrkBctBgxA2Qv4GYu",
                            Role = 2,
                            Username = "student"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Alice",
                            LastName = "Doe",
                            Password = "$2a$11$1uI8eeeAvgRapnsv9hgFZOTOHer7TLYEU1hq4b1NtmuTqmMWDapI2",
                            Role = 1,
                            Username = "teachMaster"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Bob",
                            LastName = "Doe",
                            Password = "$2a$11$KFV3EqNAQeMZgaTOYwVWQeWJV1M2ApRKdBa6jNp1iRPKt6Up7d0wK",
                            Role = 1,
                            Username = "eduGuru"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Charlie",
                            LastName = "Doe",
                            Password = "$2a$11$eDjE78HN.T6brV9jztHCq.U/nqPhGpc/gjNj48wX.KTyXrRN3YHau",
                            Role = 1,
                            Username = "profLearner"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "David",
                            LastName = "Doe",
                            Password = "$2a$11$OTMHUZOh.UQ6mvw70/ukWu5Unmr.Ebr8I17NaK8i586ii6tjcoMri",
                            Role = 1,
                            Username = "learnSculptor"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Ella",
                            LastName = "Doe",
                            Password = "$2a$11$/HwIyifXjy3pUDi8o4dxEu4nwC/tJ0JPiOpQtUnLFERIOqYd9x73S",
                            Role = 1,
                            Username = "knowledgeNinja"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Frank",
                            LastName = "Doe",
                            Password = "$2a$11$AUmZ.vbILKVH5a9jKQA0QOjOe3ohJ5jnosw/y1MpBww3RQa5Gzvce",
                            Role = 1,
                            Username = "scholarSavvy"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Grace",
                            LastName = "Doe",
                            Password = "$2a$11$RYEZMGLZQ/OPpMPca3uPQe55QZNHQVoFXu.lFhW76MrX0b0dViuH2",
                            Role = 1,
                            Username = "eduMaestro"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Hannah",
                            LastName = "Smith",
                            Password = "$2a$11$doQqTv6Sass2aqBgt.GQk.PMh8vZTxygzgdP4tGhh2Y/6sGQwGGjq",
                            Role = 1,
                            Username = "brainyTutor"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Isaac",
                            LastName = "Johnson",
                            Password = "$2a$11$DyzTNT3s13DtDV9Ij9zgy.sAG0nXFMIQeLA2wwDlw/nGInmL3JZHC",
                            Role = 1,
                            Username = "wisdomWhiz"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Tests.Test", b =>
                {
                    b.HasBaseType("Domain.Entities.Courses.CourseItem");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Scheduled")
                        .HasColumnType("timestamp with time zone");

                    b.HasIndex("CourseId");

                    b.HasDiscriminator().HasValue("Test");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 3,
                            Created = new DateTime(2024, 1, 27, 15, 23, 35, 720, DateTimeKind.Utc).AddTicks(9836),
                            IsVisible = true,
                            Name = "Write 100x hello!",
                            UserId = 1,
                            Duration = 1800,
                            End = new DateTime(2024, 1, 27, 18, 23, 35, 720, DateTimeKind.Utc).AddTicks(9842),
                            MaxAttempts = 3,
                            Password = "password",
                            Scheduled = new DateTime(2024, 1, 27, 15, 53, 35, 720, DateTimeKind.Utc).AddTicks(9837)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Courses.CourseItem", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany("CourseItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Courses.CourseXUser", b =>
                {
                    b.HasOne("Domain.Entities.Courses.Course", "Course")
                        .WithMany("Users")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany("Courses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Sessions.Session", b =>
                {
                    b.HasOne("Domain.Entities.Devices.DevicePlatform", "DevicePlatform")
                        .WithMany()
                        .HasForeignKey("DevicePlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevicePlatform");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Tests.Answers.Answer", b =>
                {
                    b.HasOne("Domain.Entities.Tests.TestSubmission", "TestSubmission")
                        .WithMany("Answers")
                        .HasForeignKey("TestSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Tests.Questions.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId", "QuestionTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("TestSubmission");
                });

            modelBuilder.Entity("Domain.Entities.Tests.Questions.Option", b =>
                {
                    b.HasOne("Domain.Entities.Tests.Questions.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId", "QuestionTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Domain.Entities.Tests.Questions.Question", b =>
                {
                    b.HasOne("Domain.Entities.Tests.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Domain.Entities.Tests.TestSubmission", b =>
                {
                    b.HasOne("Domain.Entities.Tests.Test", "Test")
                        .WithMany("Submissions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Tests.Test", b =>
                {
                    b.HasOne("Domain.Entities.Courses.Course", "Course")
                        .WithMany("Tests")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Domain.Entities.Courses.Course", b =>
                {
                    b.Navigation("Tests");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Tests.Questions.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Domain.Entities.Tests.TestSubmission", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.Navigation("CourseItems");

                    b.Navigation("Courses");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Domain.Entities.Tests.Test", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
